#!/bin/bash

export MOZ_ENABLE_WAYLAND=1
# For Android Studio
export _JAVA_AWT_WM_NONREPARENTING=1
# For Gradle
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
_JAVA_AWT_WM_NONREPARENTING=1
exec sway --unsupported-gpu
